### ISSUE TITLE
DaisyUI output.css error

### ISSUE THREAD

**Issue by DiamonC** [saadeghi/daisyui#1117]
Hi, I just installed daisyui with tailwindcss and sveltekit and while the look of everything changed, I cant use any of the classes. For example, adding class="btn" changes nothing to buttons.

There's an error I get every now and then in the terminal:

```
Not found: /dist/output.css
Error: Not found: /dist/output.css
    at resolve (file:///C:/Users/diamo/Desktop/Dev/observer/node_modules/@sveltejs/kit/src/runtime/server/index.js:273:13) 
    at Object.handle (file:///C:/Users/diamo/Desktop/Dev/observer/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:336:66)
    at respond (file:///C:/Users/diamo/Desktop/Dev/observer/node_modules/@sveltejs/kit/src/runtime/server/index.js:301:40) 
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///C:/Users/diamo/Desktop/Dev/observer/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:403:22   
```

Here's a screenshot of my file hierarchy
![image](https://user-images.githubusercontent.com/88857034/189356670-5b74c12e-e2b8-448f-9133-4e3b6b00f70e.png)

What can i do to fix this?

**Comment by saadeghi** [comment]
Looks like your CSS file name is not named `output.css` and it's `app.postcss`  

Either import `app.postcss` instead of `output.css` in your view file (it's probably in `+layout.svelte`)
```diff
<script>
-  import "../output.css"
+  import "../app.postcss"
</script>
```
or rename your `app.postcss` file to the file name you're trying to import (`output.css`)

Also make sure your CSS file includes following content:
```css
@tailwind base;
@tailwind components;
@tailwind utilities;
```

Let me know if you have any questions
