### ISSUE TITLE
bug: Error: Cannot find module 'daisyui'

### ISSUE THREAD

**Issue by ppalmeida** [saadeghi/daisyui#1834]
### What version of daisyUI are you using?

^2.51.6

### Describe your issue

I am facing issues with Prettier and DaisyUI in a brand new NextJS application.

This is the errors I'm seeing:

```log
["INFO" - 11:57:27] Formatting file:///path/to/my-project/src/components/master-page/master-page.tsx
["INFO" - 11:57:27] Using config file at '/path/to/my-project/prettier.config.cjs'
["INFO" - 11:57:27] Using ignore file (if present) at /path/to/my-project/.prettierignore
["INFO" - 11:57:27] File Info:
{
  "ignored": false,
  "inferredParser": "typescript"
}
["INFO" - 11:57:27] Detected local configuration (i.e. .prettierrc or .editorconfig), VS Code configuration will not be used
["INFO" - 11:57:27] Prettier Options:
{
  "filepath": "/path/to/my-project/src/components/master-page/master-page.tsx",
  "parser": "typescript",
  "plugins": [
    "/path/to/my-project/node_modules/prettier-plugin-tailwindcss/dist/index.js"
  ]
}
["ERROR" - 11:57:27] Error formatting document.
["ERROR" - 11:57:27] Cannot find module 'daisyui'
Require stack:
- /path/to/my-project/tailwind.config.ts
Error: Cannot find module 'daisyui'
Require stack:
- /path/to/my-project/tailwind.config.ts
    at Module._resolveFilename (node:internal/modules/cjs/loader:1010:15)
    at Function.s._resolveFilename (node:electron/js2c/utility_init:2:2740)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at _resolve (/path/to/my-project/node_modules/jiti/dist/jiti.js:1:241087)
    at jiti (/path/to/my-project/node_modules/jiti/dist/jiti.js:1:243371)
    at /path/to/my-project/tailwind.config.ts:12:49
    at jiti (/path/to/my-project/node_modules/jiti/dist/jiti.js:1:245846)
    at /path/to/my-project/node_modules/tailwindcss/lib/lib/load-config.js:37:30
    at loadConfig (/path/to/my-project/node_modules/tailwindcss/lib/lib/load-config.js:39:6)
    at Object.parse (/path/to/my-project/node_modules/prettier-plugin-tailwindcss/dist/index.js:2371:40110)
    at Object.parse (/path/to/my-project/node_modules/prettier/index.js:7515:23)
    at coreFormat (/path/to/my-project/node_modules/prettier/index.js:8829:18)
    at formatWithCursor2 (/path/to/my-project/node_modules/prettier/index.js:9021:18)
    at /path/to/my-project/node_modules/prettier/index.js:38183:12
    at Object.format (/path/to/my-project/node_modules/prettier/index.js:38197:12)
    at t.default.format (/Applications/code-portable-data/extensions/esbenp.prettier-vscode-9.12.0/dist/extension.js:1:14756)
    at t.PrettierEditProvider.provideEdits (/Applications/code-portable-data/extensions/esbenp.prettier-vscode-9.12.0/dist/extension.js:1:11429)
    at z.provideDocumentFormattingEdits (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:100:47446)
["INFO" - 11:57:27] Formatting completed in 21ms.
```

And this is my current `tailwind.config.ts` file:

```typescript
import { type Config } from "tailwindcss";

export default {
  content: ["./src/**/*.{js,ts,jsx,tsx}", "node_modules/daisyui/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        sans: ['var(--font-inter)'],
      }
    },
  },
  plugins: [require("@tailwindcss/typography"), require("daisyui")],
  daisyui: {
    themes: ['light', 'dark'],
  },
} satisfies Config;
```

Any clue what am I doing wrong? This is a very new Next 13 app with tailwind and daisyui installed.

```json
"dependencies": {
    "daisyui": "^2.51.6",
    "next": "13.3.4",
  },
  "devDependencies": {
    "@tailwindcss/typography": "^0.5.9",
    "@types/eslint": "^8.21.3",
    "autoprefixer": "^10.4.14",
    "eslint": "^8.36.0",
    "eslint-config-next": "^13.2.4",
    "postcss": "^8.4.21",
    "prettier": "^2.8.8",
    "prettier-plugin-tailwindcss": "^0.3.0",
    "tailwindcss": "^3.3.2",
  },
  ```

**Comment by saadeghi** [comment]
You don't need `node_modules/daisyui/**/*.{js,jsx,ts,tsx}` in `tailwind.config.js`

I'm not sure if that's the reason for this error but maybe deleting it would fix it.  

Also make sure daisyUI is installed and exists in `/node_modules` (run `npm i` again just in case)


If the problem still exists, I would need a reproduction repo so I can see the issue and investigate more.
