### ISSUE TITLE
bug: [plugin:vite:css] [postcss] Object.hasOwn is not a function

### ISSUE THREAD

**Issue by aboyo** [saadeghi/daisyui#1904]
### What version of daisyUI are you using?

v3.0.1

### Describe your issue

hi,

I have got an error when I running the vite(react) with v3:

```
[plugin:vite:css] [postcss] Object.hasOwn is not a function
/myproject/src/index.css
    at /myproject/node_modules/daisyui/src/theming/functions.js:73:19
    at Array.forEach (<anonymous>)
    at Object.convertColorFormat (/myproject/node_modules/daisyui/src/theming/functions.js:44:27)
    at /myproject/node_modules/daisyui/src/theming/functions.js:187:41
    at Array.forEach (<anonymous>)
    at Object.injectThemes (/myproject/node_modules/daisyui/src/theming/functions.js:182:28)
    at mainFunction (/myproject/node_modules/daisyui/src/index.js:68:43)
    at registerPlugins (/myproject/node_modules/tailwindcss/lib/lib/setupContextUtils.js:787:61)
    at createContext (/myproject/node_modules/tailwindcss/lib/lib/setupContextUtils.js:1178:5)
    at getContext (/myproject/node_modules/tailwindcss/lib/lib/setupContextUtils.js:1235:19)
    at /myproject/node_modules/tailwindcss/lib/lib/setupTrackingContext.js:117:81
    at /myproject/node_modules/tailwindcss/lib/processTailwindFeatures.js:48:11
    at plugins (/myproject/node_modules/tailwindcss/lib/plugin.js:38:63)
    at LazyResult.runOnRoot (/myproject/node_modules/postcss/lib/lazy-result.js:339:16)
    at LazyResult.runAsync (/myproject/node_modules/postcss/lib/lazy-result.js:393:26)
    at LazyResult.async (/myproject/node_modules/postcss/lib/lazy-result.js:221:30)
    at LazyResult.then (/myproject/node_modules/postcss/lib/lazy-result.js:206:17
```

but everything is fine when I use v2.6.0.

Does anyone have any ideas~?

### What browsers are you seeing the problem on?

Chrome

**Comment by saadeghi** [comment]
I think you're using a really old version of Node.js.  
`Object.hasOwn` was added in Node.js `v16.9.0`

Updating the Node.js would fix this.

**Comment by nunommc** [comment]
Same issue for me, and the answer above helped. I had v16.0 installed, I've now bumped to 18+ and works fine

**Comment by vityapro** [comment]
It's cool but if I am not able to upgrade my NodeJS?

**Comment by vityapro** [comment]
What version should I use for Node.js v14.5 ?
Can you pls update your package with additional info like:
`"engines": {
    "node": ">=14"
  },`

**Comment by saadeghi** [comment]
> What version should I use for Node.js v14.5 ?

Version 2 of daisyUI should work fine with Node 14.x as far as I know. https://v2.daisyui.com/

> Can you pls update your package with additional info

Yes. I will. Thanks for mentioning.

**Comment by edimarlnx** [comment]
The following workaround worked for me. (with NodeJs v14 - Meteor)

![image](https://github.com/saadeghi/daisyui/assets/12865401/73508a5a-dfae-46ef-a9ae-694f0dc0abf4)

**Comment by JunedSetiawan** [comment]
> It's cool but if I am not able to upgrade my NodeJS?

You can replace Object.hasOwn() method to Object.hasOwnProperty()

I also tried it on node js version 16.3.8 and it worked fine
