### ISSUE TITLE
bug: [plugin:vite:css] [postcss] Object.hasOwn is not a function

### ISSUE THREAD

**Issue by abanghendri** [saadeghi/daisyui#2065]
### What version of daisyUI are you using?

v3.1.6

### Describe your issue

Hi guys, I installed daisy js on my filamentphp, it is fresh install but I face and issue

```
[plugin:vite:css] [postcss] Object.hasOwn is not a function
/home/hendri/projects/saas-core/resources/css/app.css

    at /home/hendri/projects/saas-core/node_modules/daisyui/src/theming/functions.js:73:19
    at Array.forEach (<anonymous>)
    at Object.convertColorFormat (/home/hendri/projects/saas-core/node_modules/daisyui/src/theming/functions.js:44:27)
    at /home/hendri/projects/saas-core/node_modules/daisyui/src/theming/functions.js:187:41
    at Array.forEach (<anonymous>)
    at Object.injectThemes (/home/hendri/projects/saas-core/node_modules/daisyui/src/theming/functions.js:182:28)
    at mainFunction (/home/hendri/projects/saas-core/node_modules/daisyui/src/index.js:68:43)
    at registerPlugins (/home/hendri/projects/saas-core/node_modules/tailwindcss/lib/lib/setupContextUtils.js:787:61)
    at createContext (/home/hendri/projects/saas-core/node_modules/tailwindcss/lib/lib/setupContextUtils.js:1178:5)
    at getContext (/home/hendri/projects/saas-core/node_modules/tailwindcss/lib/lib/setupContextUtils.js:1235:19

Click outside or fix the code to dismiss.
You can also disable this overlay by setting server.hmr.overlay to false in vite.config.js.
```

this is my `package.json` file
```
{
    "private": true,
    "type": "module",
    "scripts": {
        "dev": "vite",
        "build": "vite build"
    },
    "devDependencies": {
        "@tailwindcss/forms": "^0.5.3",
        "@tailwindcss/typography": "^0.5.9",
        "autoprefixer": "^10.4.14",
        "axios": "^1.1.2",
        "daisyui": "^3.1.6",
        "laravel-vite-plugin": "^0.7.5",
        "postcss": "^8.4.24",
        "tailwindcss": "^3.3.2",
        "tippy.js": "^6.3.7",
        "vite": "^4.0.0"
    }
}
```
and my `tailwind.config.js`
```
import colors from 'tailwindcss/colors' 
import forms from '@tailwindcss/forms'
import typography from '@tailwindcss/typography' 

export default {
    content: [
        './resources/**/*.blade.php',
        './vendor/filament/**/*.blade.php', 
    ],
    darkMode: 'class',
    theme: {
        extend: {
            colors: { 
                danger: colors.rose,
                primary: colors.red,
                success: colors.green,
                warning: colors.yellow,
            }, 
        },
    },
    plugins: [
        forms, 
        typography,
        require("daisyui"),
    ],
}
```
I don't know if this a bug on daisyUI or tailwind or vite, please help me
thanks in advance :)

### What browsers are you seeing the problem on?

All browsers

**Comment by crapthings** [comment]
same issue here with meteor.js

```
=> Errors prevented startup:

   While minifying app stylesheet:
   app/node_modules/primereact/resources/themes/lara-light-indigo/theme.css: TypeError: Object.hasOwn is not a function
   at /Users/monsterstep/dev/meteor-playground/project-yzc/node_modules/daisyui/src/theming/functions.js:73:19
   at Array.forEach (<anonymous>)
   at Object.convertColorFormat (/Users/monsterstep/dev/meteor-playground/project-yzc/node_modules/daisyui/src/theming/functions.js:44:27)
   at /Users/monsterstep/dev/meteor-playground/project-yzc/node_modules/daisyui/src/theming/functions.js:187:41
   at Array.forEach (<anonymous>)
   at Object.injectThemes (/Users/monsterstep/dev/meteor-playground/project-yzc/node_modules/daisyui/src/theming/functions.js:182:28)
   at mainFunction (/Users/monsterstep/dev/meteor-playground/project-yzc/node_modules/daisyui/src/index.js:68:43)
   at registerPlugins (/Users/monsterstep/dev/meteor-playground/project-yzc/node_modules/tailwindcss/lib/lib/setupContextUtils.js:787:61)
   at createContext (/Users/monsterstep/dev/meteor-playground/project-yzc/node_modules/tailwindcss/lib/lib/setupContextUtils.js:1178:5)
   at getContext (/Users/monsterstep/dev/meteor-playground/project-yzc/node_modules/tailwindcss/lib/lib/setupContextUtils.js:1235:19)
   at /Users/monsterstep/dev/meteor-playground/project-yzc/node_modules/tailwindcss/lib/lib/setupTrackingContext.js:117:81
   at /Users/monsterstep/dev/meteor-playground/project-yzc/node_modules/tailwindcss/lib/processTailwindFeatures.js:48:11
   at plugins (/Users/monsterstep/dev/meteor-playground/project-yzc/node_modules/tailwindcss/lib/plugin.js:38:63)
   at LazyResult.runOnRoot (/Users/monsterstep/dev/meteor-playground/project-yzc/node_modules/postcss/lib/lazy-result.js:339:16)
   at LazyResult.runAsync (/Users/monsterstep/dev/meteor-playground/project-yzc/node_modules/postcss/lib/lazy-result.js:393:26)
   at LazyResult.async (/Users/monsterstep/dev/meteor-playground/project-yzc/node_modules/postcss/lib/lazy-result.js:221:30)
   at LazyResult.then (/Users/monsterstep/dev/meteor-playground/project-yzc/node_modules/postcss/lib/lazy-result.js:206:17)
   => awaited here:
   at Function.Promise.await (/Users/monsterstep/.meteor/packages/meteor-tool/.2.12.0.1bo1k4y.cx0kj++os.osx.arm64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.arm64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:56:12)
   at packages/minifyStdCSS/plugin/minify-css.js:165:21
   at /Users/monsterstep/.meteor/packages/meteor-tool/.2.12.0.1bo1k4y.cx0kj++os.osx.arm64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.arm64/dev_bundle/lib/node_modules/meteor-promise/fiber_pool.js:43:40

   While minifying app stylesheet:
   app/node_modules/primereact/resources/primereact.min.css: TypeError: Object.hasOwn is not a function
   at /Users/monsterstep/dev/meteor-playground/project-yzc/node_modules/daisyui/src/theming/functions.js:73:19
   at Array.forEach (<anonymous>)
   at Object.convertColorFormat (/Users/monsterstep/dev/meteor-playground/project-yzc/node_modules/daisyui/src/theming/functions.js:44:27)
   at /Users/monsterstep/dev/meteor-playground/project-yzc/node_modules/daisyui/src/theming/functions.js:187:41
   at Array.forEach (<anonymous>)
   at Object.injectThemes (/Users/monsterstep/dev/meteor-playground/project-yzc/node_modules/daisyui/src/theming/functions.js:182:28)
   at mainFunction (/Users/monsterstep/dev/meteor-playground/project-yzc/node_modules/daisyui/src/index.js:68:43)
   at registerPlugins (/Users/monsterstep/dev/meteor-playground/project-yzc/node_modules/tailwindcss/lib/lib/setupContextUtils.js:787:61)
   at createContext (/Users/monsterstep/dev/meteor-playground/project-yzc/node_modules/tailwindcss/lib/lib/setupContextUtils.js:1178:5)
   at getContext (/Users/monsterstep/dev/meteor-playground/project-yzc/node_modules/tailwindcss/lib/lib/setupContextUtils.js:1235:19)
   at /Users/monsterstep/dev/meteor-playground/project-yzc/node_modules/tailwindcss/lib/lib/setupTrackingContext.js:117:81
   at /Users/monsterstep/dev/meteor-playground/project-yzc/node_modules/tailwindcss/lib/processTailwindFeatures.js:48:11
   at plugins (/Users/monsterstep/dev/meteor-playground/project-yzc/node_modules/tailwindcss/lib/plugin.js:38:63)
   at LazyResult.runOnRoot (/Users/monsterstep/dev/meteor-playground/project-yzc/node_modules/postcss/lib/lazy-result.js:339:16)
   at LazyResult.runAsync (/Users/monsterstep/dev/meteor-playground/project-yzc/node_modules/postcss/lib/lazy-result.js:393:26)
   at LazyResult.async (/Users/monsterstep/dev/meteor-playground/project-yzc/node_modules/postcss/lib/lazy-result.js:221:30)
   at LazyResult.then (/Users/monsterstep/dev/meteor-playground/project-yzc/node_modules/postcss/lib/lazy-result.js:206:17)
   => awaited here:
   at Function.Promise.await (/Users/monsterstep/.meteor/packages/meteor-tool/.2.12.0.1bo1k4y.cx0kj++os.osx.arm64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.arm64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:56:12)
   at packages/minifyStdCSS/plugin/minify-css.js:165:21
   at /Users/monsterstep/.meteor/packages/meteor-tool/.2.12.0.1bo1k4y.cx0kj++os.osx.arm64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.arm64/dev_bundle/lib/node_modules/meteor-promise/fiber_pool.js:43:40

   While minifying app stylesheet:
   app/node_modules/primeicons/primeicons.css: TypeError: Object.hasOwn is not a function
   at /Users/monsterstep/dev/meteor-playground/project-yzc/node_modules/daisyui/src/theming/functions.js:73:19
   at Array.forEach (<anonymous>)
   at Object.convertColorFormat (/Users/monsterstep/dev/meteor-playground/project-yzc/node_modules/daisyui/src/theming/functions.js:44:27)
   at /Users/monsterstep/dev/meteor-playground/project-yzc/node_modules/daisyui/src/theming/functions.js:187:41
   at Array.forEach (<anonymous>)
   at Object.injectThemes (/Users/monsterstep/dev/meteor-playground/project-yzc/node_modules/daisyui/src/theming/functions.js:182:28)
   at mainFunction (/Users/monsterstep/dev/meteor-playground/project-yzc/node_modules/daisyui/src/index.js:68:43)
   at registerPlugins (/Users/monsterstep/dev/meteor-playground/project-yzc/node_modules/tailwindcss/lib/lib/setupContextUtils.js:787:61)
   at createContext (/Users/monsterstep/dev/meteor-playground/project-yzc/node_modules/tailwindcss/lib/lib/setupContextUtils.js:1178:5)
   at getContext (/Users/monsterstep/dev/meteor-playground/project-yzc/node_modules/tailwindcss/lib/lib/setupContextUtils.js:1235:19)
   at /Users/monsterstep/dev/meteor-playground/project-yzc/node_modules/tailwindcss/lib/lib/setupTrackingContext.js:117:81
   at /Users/monsterstep/dev/meteor-playground/project-yzc/node_modules/tailwindcss/lib/processTailwindFeatures.js:48:11
   at plugins (/Users/monsterstep/dev/meteor-playground/project-yzc/node_modules/tailwindcss/lib/plugin.js:38:63)
   at LazyResult.runOnRoot (/Users/monsterstep/dev/meteor-playground/project-yzc/node_modules/postcss/lib/lazy-result.js:339:16)
   at LazyResult.runAsync (/Users/monsterstep/dev/meteor-playground/project-yzc/node_modules/postcss/lib/lazy-result.js:393:26)
   at LazyResult.async (/Users/monsterstep/dev/meteor-playground/project-yzc/node_modules/postcss/lib/lazy-result.js:221:30)
   at LazyResult.then (/Users/monsterstep/dev/meteor-playground/project-yzc/node_modules/postcss/lib/lazy-result.js:206:17)
   => awaited here:
   at Function.Promise.await (/Users/monsterstep/.meteor/packages/meteor-tool/.2.12.0.1bo1k4y.cx0kj++os.osx.arm64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.arm64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:56:12)
   at packages/minifyStdCSS/plugin/minify-css.js:165:21
   at /Users/monsterstep/.meteor/packages/meteor-tool/.2.12.0.1bo1k4y.cx0kj++os.osx.arm64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.arm64/dev_bundle/lib/node_modules/meteor-promise/fiber_pool.js:43:40

   While minifying app stylesheet:
   app/client/main.css: TypeError: Object.hasOwn is not a function
   at /Users/monsterstep/dev/meteor-playground/project-yzc/node_modules/daisyui/src/theming/functions.js:73:19
   at Array.forEach (<anonymous>)
   at Object.convertColorFormat (/Users/monsterstep/dev/meteor-playground/project-yzc/node_modules/daisyui/src/theming/functions.js:44:27)
   at /Users/monsterstep/dev/meteor-playground/project-yzc/node_modules/daisyui/src/theming/functions.js:187:41
   at Array.forEach (<anonymous>)
   at Object.injectThemes (/Users/monsterstep/dev/meteor-playground/project-yzc/node_modules/daisyui/src/theming/functions.js:182:28)
   at mainFunction (/Users/monsterstep/dev/meteor-playground/project-yzc/node_modules/daisyui/src/index.js:68:43)
   at registerPlugins (/Users/monsterstep/dev/meteor-playground/project-yzc/node_modules/tailwindcss/lib/lib/setupContextUtils.js:787:61)
   at createContext (/Users/monsterstep/dev/meteor-playground/project-yzc/node_modules/tailwindcss/lib/lib/setupContextUtils.js:1178:5)
   at getContext (/Users/monsterstep/dev/meteor-playground/project-yzc/node_modules/tailwindcss/lib/lib/setupContextUtils.js:1235:19)
   at /Users/monsterstep/dev/meteor-playground/project-yzc/node_modules/tailwindcss/lib/lib/setupTrackingContext.js:117:81
   at /Users/monsterstep/dev/meteor-playground/project-yzc/node_modules/tailwindcss/lib/processTailwindFeatures.js:48:11
   at plugins (/Users/monsterstep/dev/meteor-playground/project-yzc/node_modules/tailwindcss/lib/plugin.js:38:63)
   at LazyResult.runOnRoot (/Users/monsterstep/dev/meteor-playground/project-yzc/node_modules/postcss/lib/lazy-result.js:339:16)
   at LazyResult.runAsync (/Users/monsterstep/dev/meteor-playground/project-yzc/node_modules/postcss/lib/lazy-result.js:393:26)
   at LazyResult.async (/Users/monsterstep/dev/meteor-playground/project-yzc/node_modules/postcss/lib/lazy-result.js:221:30)
   at LazyResult.then (/Users/monsterstep/dev/meteor-playground/project-yzc/node_modules/postcss/lib/lazy-result.js:206:17)
   => awaited here:
   at Function.Promise.await (/Users/monsterstep/.meteor/packages/meteor-tool/.2.12.0.1bo1k4y.cx0kj++os.osx.arm64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.arm64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:56:12)
   at packages/minifyStdCSS/plugin/minify-css.js:165:21
   at /Users/monsterstep/.meteor/packages/meteor-tool/.2.12.0.1bo1k4y.cx0kj++os.osx.arm64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.arm64/dev_bundle/lib/node_modules/meteor-promise/fiber_pool.js:43:40

=> Your application has errors. Waiting for file change.
=> Started MongoDB.
```

**Comment by wangyi12358** [comment]
I also encountered this issue, but I resolved it by switching to Node18. You can give it a try.

**Comment by saadeghi** [comment]
Updating your Node.js fixes this.
