### ISSUE TITLE
bug: DaisyUI does not work with Next.js

### ISSUE THREAD

**Issue by drosi94** [saadeghi/daisyui#222]
Hello, I would like to use DaisyUI to my nextjs pwa but I have an issue using the library. In storybook works as expected but in next.js I see this log all the time and my PWA does not load

It's a monorepo and I have created a shared package that I use daisyUI there with react components that I import to my PWA

![Screenshot 2021-10-02 at 1 11 37 PM](https://user-images.githubusercontent.com/3253526/135711903-2235b5a2-6730-4e93-9e9f-20bec867b516.png)

I attach the config files

next.config.js

```const withPlugins = require('next-compose-plugins')
const withTM = require('next-transpile-modules')(['@forest-restoration/shared'])
const withPWA = require('next-pwa')
const withImages = require('next-images')
const { i18n } = require('./next-i18next.config')

const STUDIO_REWRITE = {
  source: '/studio/:path*',
  destination:
    process.env.NODE_ENV === 'development'
      ? 'http://localhost:3333/studio/:path*'
      : 'https://forestrestoration.sanity.studio/:path*',
}

module.exports = withPlugins(
  [
    withPWA({
      webpack: (config) => {
        config.resolve.fallback = {
          fs: false,
          module: false,
          path: false,
          os: false,
          stream: false,
        }
        return config
      },
      pwa: {
        dest: 'public',
        register: true,
        skipWaiting: true,
      },
    }),
    withImages,
    withTM(),
  ],
  {
    pageExtensions: ['page.js', 'page.tsx', 'page.ts'],
    reactStrictMode: true,
    images: {},
    i18n,
    redirects() {
      return [
        process.env.NEXT_PUBLIC_MAINTENANCE_MODE === 'true'
          ? {
              source:
                '/((?!maintenance)(?!_next)(?!static|(?!image))(?!favicon-16x16.png)(?!favicon-32x32.png)(?!icon-192x192.png)(?!manifest.json)(?!themeToggle.js).*)',
              destination: '/maintenance',
              permanent: false,
            }
          : null,
      ].filter(Boolean)
    },
    rewrites: () => [STUDIO_REWRITE],
    images: {
      domains: ['cdn.sanity.io'],
    },
  }
)
```

tailwind.config.js

```
module.exports = {
  mode: 'jit',
  purge: ['*.{js,ts,jsx,tsx}'],

  variants: {},
  plugins: [
    require('tailwindcss-filters'),
    require('@tailwindcss/typography'),
    require('tailwindcss-hyphens'),
    require('@tailwindcss/line-clamp'),
    require('tailwind-accent-color')(),
    require('daisyui'),
  ],
  daisyui: {
    themes: [
      {
        light: {
          primary: '#a991f7' /* Primary color */,
          'primary-focus': '#8462f4' /* Primary color - focused */,
          'primary-content': '#ffffff' /* Foreground content color to use on primary color */,

          secondary: '#f6d860' /* Secondary color */,
          'secondary-focus': '#f3cc30' /* Secondary color - focused */,
          'secondary-content': '#ffffff' /* Foreground content color to use on secondary color */,

          accent: '#37cdbe' /* Accent color */,
          'accent-focus': '#2aa79b' /* Accent color - focused */,
          'accent-content': '#ffffff' /* Foreground content color to use on accent color */,

          neutral: '#3d4451' /* Neutral color */,
          'neutral-focus': '#2a2e37' /* Neutral color - focused */,
          'neutral-content': '#ffffff' /* Foreground content color to use on neutral color */,

          'base-100': '#ffffff' /* Base color of page, used for blank backgrounds */,
          'base-200': '#f9fafb' /* Base color, a little darker */,
          'base-300': '#d1d5db' /* Base color, even more darker */,
          'base-content': '#1f2937' /* Foreground content color to use on base color */,

          info: '#2094f3' /* Info */,
          success: '#009485' /* Success */,
          warning: '#ff9900' /* Warning */,
          error: '#ff5724' /* Error */,
        },
        dark: {
          primary: '#f79191' /* Primary color */,
          'primary-focus': '#f46262' /* Primary color - focused */,
          'primary-content': '#ffffff' /* Foreground content color to use on primary color */,

          secondary: '#f6d860' /* Secondary color */,
          'secondary-focus': '#f3cc30' /* Secondary color - focused */,
          'secondary-content': '#ffffff' /* Foreground content color to use on secondary color */,

          accent: '#37cdbe' /* Accent color */,
          'accent-focus': '#2aa79b' /* Accent color - focused */,
          'accent-content': '#ffffff' /* Foreground content color to use on accent color */,

          neutral: '#3d4451' /* Neutral color */,
          'neutral-focus': '#2a2e37' /* Neutral color - focused */,
          'neutral-content': '#ffffff' /* Foreground content color to use on neutral color */,

          'base-100': '#ffffff' /* Base color of page, used for blank backgrounds */,
          'base-200': '#f9fafb' /* Base color, a little darker */,
          'base-300': '#d1d5db' /* Base color, even more darker */,
          'base-content': '#1f2937' /* Foreground content color to use on base color */,

          info: '#2094f3' /* Info */,
          success: '#009485' /* Success */,
          warning: '#ff9900' /* Warning */,
          error: '#ff5724' /* Error */,
        },
      },
    ],
  },
}
```

**Comment by saadeghi** [comment]
@drosi94 It's hard to debug without a repo link
 But I don't think your purge config is good.  
I think `purge: ['*.{js,ts,jsx,tsx}'],` will only target the files in root directory.
Use something like this (according to your files structure):
```
purge: [
  './pages/**/*.{js,ts,jsx,tsx}', 
  './components/**/*.{js,ts,jsx,tsx}', 
  './layouts/**/*.{js,ts,jsx,tsx}', 
  './lib/**/*.{js,ts,jsx,tsx}'
],
```

**Comment by drosi94** [comment]
You are Right

It's here https://github.com/drosi94/forest-restoration-ui

I will try to change the purge config thanks

**Comment by drosi94** [comment]
I changed the purge configuration but I got the same problem you can check it out on `feature/add-daisy` branch

**Comment by saadeghi** [comment]
@drosi94 this lockfile is not correct. I'm just getting errors about a lot of missing packages after install 😐

**Comment by drosi94** [comment]
Could you retry I forgot to commit some latest changes. I'm sorry.

**Comment by saadeghi** [comment]
@drosi94 
```console
yarn start:pwa:env


yarn run v1.22.11
$ lerna run dev:env --scope @forest-restoration/pwa --stream
lerna notice cli v4.0.0
lerna notice filter including "@forest-restoration/pwa"
lerna info filter [ '@forest-restoration/pwa' ]
lerna info Executing command in 1 package: "yarn run dev:env"
@forest-restoration/pwa: $ next dev
@forest-restoration/pwa: ready - started server on 0.0.0.0:3000, url: http://localhost:3000
@forest-restoration/pwa: next-transpile-modules - DEPRECATED - fallbacking to previous module resolution system for module "@forest-restoration/shared", you can now just pass the name of the package to transpile and it will detect its real path without you having to pass a sub-module.
@forest-restoration/pwa: Error: failed to load next.config.js, see more info here https://nextjs.org/docs/messages/next-config-error
@forest-restoration/pwa: Error: next-transpile-modules - an unexpected error happened when trying to resolve "@forest-restoration/shared". Are you sure the name module you are trying to transpile is correct, and it has a "main" or an "exports" field?
@forest-restoration/pwa: Error: Can't resolve '@forest-restoration/shared' in '/Users/pouya/Sites/forest-restoration-ui/packages/pwa'
@forest-restoration/pwa:     at getPackageRootDirectory (/Users/pouya/Sites/forest-restoration-ui/node_modules/next-transpile-modules/src/next-transpile-modules.js:173:17)
@forest-restoration/pwa:     at Array.map (<anonymous>)
@forest-restoration/pwa:     at withTM (/Users/pouya/Sites/forest-restoration-ui/node_modules/next-transpile-modules/src/next-transpile-modules.js:185:34)
@forest-restoration/pwa:     at Object.<anonymous> (/Users/pouya/Sites/forest-restoration-ui/packages/pwa/next.config.js:35:5)
@forest-restoration/pwa:     at Module._compile (internal/modules/cjs/loader.js:1068:30)
@forest-restoration/pwa:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
@forest-restoration/pwa:     at Module.load (internal/modules/cjs/loader.js:933:32)
@forest-restoration/pwa:     at Function.Module._load (internal/modules/cjs/loader.js:774:14)
@forest-restoration/pwa:     at Module.require (internal/modules/cjs/loader.js:957:19)
@forest-restoration/pwa:     at require (internal/modules/cjs/helpers.js:88:18)
@forest-restoration/pwa: error Command failed with exit code 1.
@forest-restoration/pwa: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run dev:env exited 1 in '@forest-restoration/pwa'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by saadeghi** [comment]
Also, here's an example with Next.js and daisyUI: https://github.com/saadeghi/daisyui/tree/master/examples/nextjs-daisyui-headlessui-master
I'm closing this issue because it's not a daisyUI bug.
But feel free to continue the conversation. I'll be glad to help.

**Comment by drosi94** [comment]
That's a strange error that you get, I will investigate it, thanks!!

Back in our main issue... It just takes about 5 minutes to compile the  DaisyUI css. I will check why it takes so long. Maybe some issues with the purge or the imports.

**Comment by saadeghi** [comment]
@drosi94 5 minutes is not normal at all. I had a nextjs project with more than 40 pages and the whole Tailwind+daisyUI build was about 700 milliseconds.

**Comment by drosi94** [comment]
I fixed the issue, I had to make some changes to my purge config because of my setup. Now it compiles really fast!

One issue that I find out are these weird CSS variables

![Screenshot 2021-10-03 at 4 28 55 AM](https://user-images.githubusercontent.com/3253526/135736325-f7ab2796-acb5-480f-aef9-2c6d1451fd64.png)

```
--p: 158 96% 29.2%;
    --pf: 158 96.4% 21.6%;
    --pc: 0 0% 92.2%;
    --s: 240 3.8% 46.1%;
    --sf: 240 5.3% 26.1%;
    --sc: 0 0% 92.2%;
    --a: 158 96% 29.2%;
    --af: 158 96.4% 21.6%;
    -webkit---ac: 0 0% 92.2%;
    --ac: 0 0% 92.2%;
    --n: 240 3.8% 46.1%;
    --nf: 240 5.9% 10%;
    --nc: 0 0% 92.2%;
    -b1: 0 0% 100%;
    -b2: 0 0% 91%;
    -b3: 216 8.5% 76.9%;
    --bc: 0 0% 37.6%;
    --in: 217 91.2% 59.8%;
    --su: 158 96% 29.2%;
    --wa: 25 95% 53.1%;
    --er: 0 84.2% 60.2%;
    background-color: hsla(var(--b1)/var(--tw-bg-opacity,1));
    color: hsla(var(--bc)/var(--tw-text-opacity,1));
```

**Comment by saadeghi** [comment]
@drosi94 great 👍
[Here](https://github.com/drosi94/forest-restoration-ui/blob/e100a92ff9024727a766790446f1e522f7fbde7e/packages/pwa/tailwind.config.js#L89) you have to use hex colors. Currently only hex colors are acceptable and the hex color values automatically get converted to separate HSLA values underneath. It's different from Tailwind's internal color function.

**Comment by drosi94** [comment]
Thank you I will try it out

**Comment by drosi94** [comment]
@saadeghi  Thank you for your immediate help. Whenever I have time I will try to contribute to daisyUI. It's a great library!
