### ISSUE TITLE
bug: My project doesnt load because of undefined (reading 'r') error after updating to v4

### ISSUE THREAD

**Issue by sveltarne** [saadeghi/daisyui#2501]
### What version of daisyUI are you using?

4.0.1

### Reproduction URL

https://codeberg.org/diamonc/observer

### Describe your issue

any page gives you the error:
```
TypeError: [postcss] Cannot read properties of undefined (reading 'r')
    at luminance (/home/diamonc/Dev/observer/node_modules/culori/src/wcag.js:12:20)
    at contrast (/home/diamonc/Dev/observer/node_modules/culori/src/wcag.js:19:11)
    at Object.isDark (/home/diamonc/Dev/observer/node_modules/daisyui/src/theming/functions.js:8:9)
    at Object.generateForegroundColorFrom (/home/diamonc/Dev/observer/node_modules/daisyui/src/theming/functions.js:26:45)
    at /home/diamonc/Dev/observer/node_modules/daisyui/src/theming/functions.js:91:34
    at Array.forEach (<anonymous>)
    at Object.convertColorFormat (/home/diamonc/Dev/observer/node_modules/daisyui/src/theming/functions.js:42:27)
    at /home/diamonc/Dev/observer/node_modules/daisyui/src/theming/functions.js:155:55
    at Array.forEach (<anonymous>)
    at /home/diamonc/Dev/observer/node_modules/daisyui/src/theming/functions.js:154:32 {
  code: '',
  plugin: 'vite:css',
  id: '/home/diamonc/Dev/observer/src/app.css'
}
```
This error also appears in the console. I should note that you would need to update to daisyUI 4 after cloning the repo if you're trying to reproduce, as I haven't pushed the changes to the repo because it crashes it.

**Comment by VictorGlindasPaf** [comment]
Getting something similar when trying to compile out NextJS app with V4:
```
⨯ ./src/styles/globals.css.webpack[javascript/auto]!=!../node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[12].oneOf[12].use[2]!../node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[12].oneOf[12].use[3]!./src/styles/globals.css
TypeError: Cannot read properties of undefined (reading 'l')
    at Array.map (<anonymous>)
    at Array.reduce (<anonymous>)
    at Array.forEach (<anonymous>)
    at Array.forEach (<anonymous>)
    at Array.forEach (<anonymous>)
Import trace for requested module:
./src/styles/globals.css.webpack[javascript/auto]!=!../node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[12].oneOf[12].use[2]!../node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[12].oneOf[12].use[3]!./src/styles/globals.css
./src/styles/globals.css
```

**Comment by CDzungx** [comment]
Same problem

**Comment by sveltarne** [comment]
This is the same issue as #2496, go there to talk about this.
