### ISSUE TITLE
Build failing after update to 1.14.4

### ISSUE THREAD

**Issue by sidharthv96** [saadeghi/daisyui#252]
Issue is persisting in 1.14.5 also. 

Code: https://github.com/mermaid-js/mermaid-live-editor/blob/1f4f4a94a371ac08e90f4b2d52d56533a1a1a99d/src/app.postcss#L1-L10

Complete logs: https://github.com/mermaid-js/mermaid-live-editor/runs/3917211510?check_suite_focus=true

```bash
$ svelte-kit build
vite v2.6.7 building for production...
(node:1963) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at /home/runner/work/mermaid-live-editor/mermaid-live-editor/node_modules/chai/package.json.
Update this package.json to use a subpath pattern like "./*".
(Use `node --trace-deprecation ...` to show where the warning was created)
transforming...

warn - You have enabled the JIT engine which is currently in preview.
warn - Preview features are not covered by semver, may introduce breaking changes, and can change at any time.

🌼 daisyUI components 1.14.5  https://github.com/saadeghi/daisyui
  ✔︎ Including:  base, components, themes[21], utilities
  

🌼 daisyUI components 1.14.5  https://github.com/saadeghi/daisyui
  ✔︎ Including:  base, components, themes[21], utilities
  
✓ 57 modules transformed.
[vite:css] Cannot read properties of undefined (reading '5')
file: /home/runner/work/mermaid-live-editor/mermaid-live-editor/src/app.postcss
> Cannot read properties of undefined (reading '5')
TypeError: Cannot read properties of undefined (reading '5')
    at Parser.parentheses (/home/runner/work/mermaid-live-editor/mermaid-live-editor/node_modules/postcss-selector-parser/dist/parser.js:859:65)
    at Parser.parse (/home/runner/work/mermaid-live-editor/mermaid-live-editor/node_modules/postcss-selector-parser/dist/parser.js:1058:14)
    at Parser.loop (/home/runner/work/mermaid-live-editor/mermaid-live-editor/node_modules/postcss-selector-parser/dist/parser.js:1039:12)
    at new Parser (/home/runner/work/mermaid-live-editor/mermaid-live-editor/node_modules/postcss-selector-parser/dist/parser.js:164:10)
    at Processor._root (/home/runner/work/mermaid-live-editor/mermaid-live-editor/node_modules/postcss-selector-parser/dist/processor.js:53:18)
    at Processor._runSync (/home/runner/work/mermaid-live-editor/mermaid-live-editor/node_modules/postcss-selector-parser/dist/processor.js:100:21)
    at Processor.processSync (/home/runner/work/mermaid-live-editor/mermaid-live-editor/node_modules/postcss-selector-parser/dist/processor.js:197:23)
    at /home/runner/work/mermaid-live-editor/mermaid-live-editor/node_modules/postcss-minify-selectors/dist/index.js:214:45
    at /home/runner/work/mermaid-live-editor/mermaid-live-editor/node_modules/postcss/lib/container.js:96:18
    at /home/runner/work/mermaid-live-editor/mermaid-live-editor/node_modules/postcss/lib/container.js:55:18
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.
```

**Comment by saadeghi** [comment]
@sidharthv96 Are you sure this is an issue from daisyUI?
I cloned your repo, I uninstalled `daisyui`, removed it from `tailwind.config.js` and removed the custom `apply` lines from `app.postcss` but still I can't build the app:
```
[vite] Error when evaluating SSR module /src/lib/components/view.svelte:
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /mermaid-live-editor/node_modules/d3/src/index.js
require() of ES modules is not supported.
```
```
require() of /mermaid-live-editor/node_modules/d3/src/index.js from /mermaid-live-editor/node_modules/mermaid/dist/mermaid.core.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
```

**Comment by sidharthv96** [comment]
That's weird.
The only thing I had to change to get it to build was change daisyUI version.
The dependabot PR was for 1.14.5. That build failed.
Then I tried instal ling locally, with version set as "^1.14.5". Failed.
"^1.14.2" : Failed (I guess because it was fetching 1.14.5 version)
"1.14.2": Success (Exact version)
"1.14.5": Failed
"1.14.4": Failed
"1.14.3": Success

The error you seem to get is an old one which was fixed recently.

The latest master build has passed with DaisyUI(1.14.3): https://github.com/mermaid-js/mermaid-live-editor/runs/3917405439

**Comment by saadeghi** [comment]
I think what might cause this error is using CSS `:where()` selector [here on one of themes](https://github.com/saadeghi/daisyui/blame/f8f6badc2d1315896fc91907f54102dd461087c9/src/colors/themes.js#L513)
And apparently Sveltekit doesn't see that as a valid selector 🤔   
I'm trying `*:where()` instead of `:where()` in version `1.14.7`  
Can you please try the latest version (1.14.7) and see if the error still exists?
