### ISSUE TITLE
bug: error: Cannot find module '../dist/utilities'

### ISSUE THREAD

**Issue by leimantas** [saadeghi/daisyui#2543]
### What version of daisyUI are you using?

4.2.0

### Reproduction URL

dont have

### Describe your issue

After latest update to 4.2.0:

```
[ERROR] Build failed with 1 error:
error: Cannot find module '../dist/utilities'
Require stack:
- /node_modules/daisyui/src/index.js [plugin css-file]
```

Downgrading to 4.1.1 - everything works.

**Comment by luizkowalski** [comment]
hey @saadeghi 
I just updated to 4.2.2 and now I'm seeing this too:


```shell
css        | Error: Cannot find module '../dist/utilities.cjs'
css        | Require stack:
css        | - /Users/luiz/Projects/sumiu/node_modules/daisyui/src/index.js
css        |     at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
css        |     at Function.resolve (node:internal/modules/helpers:187:19)
css        |     at _resolve (/Users/luiz/Projects/sumiu/node_modules/jiti/dist/jiti.js:1:251148)
css        |     at jiti (/Users/luiz/Projects/sumiu/node_modules/jiti/dist/jiti.js:1:253746)
css        |     at /Users/luiz/Projects/sumiu/node_modules/daisyui/src/index.js:10:21
css        |     at evalModule (/Users/luiz/Projects/sumiu/node_modules/jiti/dist/jiti.js:1:256443)
css        |     at jiti (/Users/luiz/Projects/sumiu/node_modules/jiti/dist/jiti.js:1:254371)
css        |     at /Users/luiz/Projects/sumiu/tailwind.config.js:15:3
css        |     at evalModule (/Users/luiz/Projects/sumiu/node_modules/jiti/dist/jiti.js:1:256443)
css        |     at jiti (/Users/luiz/Projects/sumiu/node_modules/jiti/dist/jiti.js:1:254371) {
css        |   code: 'MODULE_NOT_FOUND',
css        |   requireStack: [ '/Users/luiz/Projects/sumiu/node_modules/daisyui/src/index.js' ]
```

**Comment by leimantas** [comment]
Same

**Comment by saadeghi** [comment]
Sorry I fucked up 🫣

**Comment by leimantas** [comment]
> Sorry I fucked up 🫣

no problems :D

**Comment by luizkowalski** [comment]
we all do it lol

**Comment by saadeghi** [comment]
Must be fixed now in `4.2.3`

**Comment by leimantas** [comment]
yes :) it works now!

**Comment by saadeghi** [comment]
(◍•ᴗ•◍)
