### ISSUE TITLE
bug: The theme color is incorrect in yarn serve mode after Docusaurus is built

### ISSUE THREAD

**Issue by inrhor** [saadeghi/daisyui#2987]
### What version of daisyUI are you using?

latest

### Which browsers are you seeing the problem on?

Edge

### Reproduction URL

https://stackblitz.com/edit/github-snyqqa?file=src/pages/index.js

### Describe your issue

Both the new and old versions of Docusaurus and DaisyUI encounter this issue. Reproducing steps are as follows:

The Windows system theme is set to dark mode.
After running yarn build and yarn serve, Docusaurus displays light colors, while DaisyUI displays dark colors.
The displayed effects differ between development mode using yarn start and service mode using yarn serve.

![1](https://github.com/saadeghi/daisyui/assets/67991284/c6063910-3235-4ad8-861d-cdfe2cac614a)

**Comment by saadeghi** [comment]
On your link, when I run ` yarn build && yarn serve` I get this error
```
SyntaxError: Unexpected identifier '𝐬𝐛_𝐞𝐱𝐩𝐨𝐬𝐞'
[ERROR] Unable to build website for locale en.
[ERROR] Error: Failed to compile with errors.
    at eval (file:///home/projects/github-snyqqa/node_modules/@docusaurus/core/lib/webpack/utils.js:207:24)
    at eval (file:///home/projects/github-snyqqa/node_modules/webpack/lib/MultiCompiler.js:554:14)
    at processQueueWorker (file:///home/projects/github-snyqqa/node_modules/webpack/lib/MultiCompiler.js:491:6)
    at _0x3b802d (https://githubsnyqqa-0xfm-v1vb2tl8.w-credentialless-staticblitz.com/blitz.41fbae16.js:352:155078)
    at https://githubsnyqqa-0xfm-v1vb2tl8.w-credentialless-staticblitz.com/blitz.41fbae16.js:352:154835
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by fattila16** [comment]
I had a similar problem where for some reason when I built my docusaurus project for production my daisy-ui overwrites were not working. In the end I hacked it with overwriting the css variables in the docusaurus specific `src/css/custom.css` file like this:
```css
* {
  --s: <insert your color>;
}
```
In this case I wanted to override the secondary color to something other than the default one. This is not something that I would recommend btw.
